feat: assignment list filtered by department
dinis-rodrigues/tsb-web-app-react pull request #46
Opened 2022-09-21 19:54 UTC by Salg-0

2022-09-22 09:19 UTC, dinis-rodrigues requested changes

2022-09-22 09:19 UTC, dinis-rodrigues commented on src/utils/generalFunctions.tsx
> +      }
Acho que este `if (department)` não é necessário certo? Porque no `useEffect` já estás a fazer esse check

2022-09-22 10:12 UTC, Salg-0 commented on src/utils/generalFunctions.tsx
> +      }
o if department faz a distinção se esta funcão está a ser usada para fazer a assignment ou para o budget.
filtra se lhe é mandado um department (tasks) e não caso contrario (budget)

2022-09-22 10:38 UTC, dinis-rodrigues commented on src/utils/generalFunctions.tsx
> +      }
Tens razão, confundi o nesting dos `if's`

2022-09-22 10:42 UTC, dinis-rodrigues commented on src/utils/generalFunctions.tsx
> +      }
Mas adicionalmente, com este código, quando tivermos no board de um departamento. Só vamos poder escolher pessoas desse departamento para designar uma task, certo?

2022-09-22 11:09 UTC, Salg-0 commented on src/utils/generalFunctions.tsx
> +      }
sim sim, penso que depois com o adicionamento de um novo board para o geral não vai haver problema.
Mas se calhar posso re-ordenar a lista de modo a em vez de so aparecerem malta da área, aparecem apenas primeiro, não sei qual é a importãncia de ter toda a gente lá.

2022-09-22 15:18 UTC, dinis-rodrigues commented on src/utils/generalFunctions.tsx
> +      }
Essa de meter os da area primeiro parace-me melhor. Só porque do meu ponto de vista é preferivel aparecerem todos na lista do que so alguns. Não sei, pode haver vezes em que designas tarefas a outra pessoa fora do departamento

2022-09-23 09:46 UTC, dinis-rodrigues approved these changes
Parece estar tudo ok! Podes dar merge 🚀

2022-09-23 12:23 UTC, merged